version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ask_book
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    logging:
      driver: none
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ask_book
      - SECRET_KEY_BASE=SECRET_KEY_BASE

volumes:
  db:
    driver: local
